import type { Metadata } from "next";
import { Bubblegum_Sans, PT_Serif, Arvo, Merriweather } from "next/font/google";

import { Navbar } from "@/components/Navbar";

import "./globals.css";

const bubblegum = Bubblegum_Sans({
  variable: "--font-bubblegum",
  subsets: ["latin"],
  weight: ["400"],
});

const ptSerif = Merriweather({
  variable: "--font-ptserif",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${bubblegum.variable} ${ptSerif.variable} ${ptSerif.className} antialiased`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
